### PR TITLE
Registration notebooks rmod

### PR DESCRIPTION
**Pull request by richardbeare**
Various, minor, changes to make code more R-like.

As a note - there are some potential changes that would use extra packages - more beautiful plotting with ggplot2 and some neater syntax for the mapply calls using purrr::map. Let me know if you'd like to
explore any of that side of things

### CODE REVIEW

**Comment by zivy** [comment]
It would be great if you did the nicer plotting (ggplot) and neater syntax (purrr), the goal is to make the notebooks follow good practices familiar to R developers. 

More concrete points:

In notebook 61 we have the AddCommand commented out for all registrations, do we remove them or should we follow the approach from notebook 60, plot the similarity metric graph at the end of the iterations?

In theory we should be able to do animations the same way we do it in the Python notebooks, loop(clear_cell_output+plot). Currently the ir kernel does not provide a programatic way for clear_cell_output. I inquired with the developers (https://github.com/IRkernel/IRkernel/issues/432), but I'm not holding my breath for them to implement it. Hopefully they do and then we have the ability to do real-time animations.

Notebook 65, really liked the graph you added displaying the lung volume, why didn't I think of that. Is there a reason to keep the textual output? I would be in favor of removing it, unless you think there is a reason to keep it. 

Notebook 65, the Execute methods for the HausdorffDistanceImageFilter and LabelOverlapMeasuresImageFilter no longer return a value (empty image), no need to assign to dev_null. I guess your SimpleITK install is not up to date.

**Comment by richardbeare** [comment]
I think it is probably enough to demonstrate the AddCommand in one notebook, rather than repeating ourselves. Perhaps comments in text is enough to point out that it is a key tool when setting up the registration.

No need to keep the text volumes. I'd better update my SimpleITK before going any further.

I'll work on ggplot/purrr versions.

**Comment by richardbeare** [comment]
I've added some ggplot2 examples and cleaned up a couple of mapply calls using either sapply or map2.

I think there is another in registration_utilities that I'd recommend rewriting as a loop - I think it is good to avoid <<- where possible. Also some cases in which might be clearer with map

**Comment by zivy** [comment]
I'll merge with my branch, clean up some things (delete the AddCommand stuff in notebook 61, etc.) and then push this branch to the main repository. Thanks for upgrading the code to the R best practices approach.

**Pull request merged**
